# Generated by Django 5.1.6 on 2025-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('explicit', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('audio_features', models.JSONField(blank=True, null=True)),
                ('spotify_track_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
