# Generated by Django 5.1.6 on 2025-02-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_song_acousticness_song_danceability_song_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
